version: '3.7'

services:
  gateway:
    build: gateway
    env_file: .env
    volumes:
      - ./gateway/code:/code
    ports:
      - 80:${TORNADO_PORT}

  mq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672

